name: Build and Deploy Next.js to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: "Checkout Github Action"
        uses: actions/checkout@v4

      - name: "Set up Node.js version"
        uses: actions/setup-node@v3
        with:
          node-version: "20.x" # Pastikan versi ini cocok dengan yang di Azure

      - name: "npm install and build"
        run: |
          npm install
          npm run build

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "Next-Court-Vision"
          # Hapus slot-name jika Anda tidak menggunakan Deployment Slots
          # slot-name: 'Production'

          # 'package: .' akan mengambil semua file di direktori kerja,
          # TERMASUK folder .next yang baru dibuat.
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4CE85ABCFB254BE9A98288BEBA8CA44D }}
