# .github/workflows/main.yml

name: Build and deploy Node.js app to Azure Web App - Next-Court-Vision

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: "Checkout Github Action"
        uses: actions/checkout@v4

      - name: "Set up Node.js version"
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: "npm install and build"
        run: |
          npm install
          npm run build

      # LANGKAH BARU: Hapus node_modules setelah build untuk paket yang ramping
      - name: "Remove node_modules for deployment"
        run: rm -rf node_modules

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "Next-Court-Vision"
          slot-name: "Production"
          package: . # Deploy paket ramping (tanpa node_modules)
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4CE85ABCFB254BE9A98288BEBA8CA44D }}
