name: Build and Deploy Standalone Next.js to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: "Checkout Github Action"
        uses: actions/checkout@v4

      - name: "Set up Node.js version"
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: "npm install and build"
        run: |
          npm install
          npm run build

      - name: "Prepare Standalone Package"
        run: |
          # Buat direktori baru untuk paket deployment
          mkdir -p deployment_package
          # Salin folder standalone
          cp -r .next/standalone/. deployment_package/
          # Salin folder static assets
          cp -r .next/static deployment_package/.next/static
          # Salin folder public assets
          cp -r public deployment_package/public

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "Next-Court-Vision"
          slot-name: "Production"
          # Arahkan package ke direktori yang sudah kita siapkan
          package: ./deployment_package
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4CE85ABCFB254BE9A98288BEBA8CA44D }}
